# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: with-utf8
version: 0.0.0
synopsis: Get your IO right on the first try
description: |
  This minimalistic library helps you navigate the world of text encodings
  avoiding @invalid argument (invalid byte sequence)@
  and @invalid argument (invalid character)@ in runtime.

  The two most important modules are:

    * "Main.Utf8"
    * "System.IO.Utf8"

  See <https://serokell.io/blog/haskell-with-utf8 this blog post> for why this
  library exists and what exactly it does.
category: IO

author: Kirill Elagin <kirelagin@serokell.io>
copyright: 2020 Serokell
license-file: LICENSES/MPL-2.0.txt

github: serokell/haskell-with-utf8

extra-doc-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: lib

  dependencies:
    - base >= 4.10 && < 4.14
    - safe-exceptions >= 0.1  # only really needed for polymorphic bracket
    - text >= 0.7

tests:
  with-utf8-test:
    source-dirs: test
    main: Test.hs

    dependencies:
      - with-utf8

      - base
      - deepseq
      - safe-exceptions
      - temporary
      - text
      - unix

      - hedgehog
      - HUnit
      - tasty
      - tasty-hedgehog
      - tasty-hunit

    build-tools:
      - tasty-discover:tasty-discover
