# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

name: with-utf8
version: 1.0.2.4
synopsis: Get your IO right on the first try
description: |
  This minimalistic library helps you navigate the world of text encodings
  avoiding @invalid argument (invalid byte sequence)@
  and @invalid argument (invalid character)@ in runtime.

  See <https://serokell.io/blog/haskell-with-utf8 this blog post> for why this
  library exists and what exactly it does.

  The two most important modules are:

    * "Main.Utf8"
    * "System.IO.Utf8"
category: IO

author: Kirill Elagin <kirelagin@serokell.io>
copyright: 2020 Serokell
license-file: LICENSES/MPL-2.0.txt

github: serokell/haskell-with-utf8

extra-doc-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.10 && < 4.19
  - text >= 0.7 && < 2.1

library:
  source-dirs: lib

  dependencies:
    - safe-exceptions >= 0.1 && < 0.2  # only really needed for polymorphic bracket

executables:
  utf8-troubleshoot:
    source-dirs: app/utf8-troubleshoot
    main: Main.hs

    c-sources: app/utf8-troubleshoot/cbits/locale.c

    dependencies:
      - directory >= 1.2.5.0 && < 1.4
      - filepath >= 1.0 && < 1.5
      - process >= 1.0.1.1 && < 1.7
      - safe-exceptions
      - th-env >= 0.1.0.0 && < 0.2

tests:
  with-utf8-test:
    source-dirs: test
    main: Test.hs

    dependencies:
      - with-utf8

      - deepseq
      - safe-exceptions
      - temporary
      - unix

      - hedgehog
      - HUnit
      - tasty
      - tasty-hedgehog
      - tasty-hunit

    build-tools:
      - tasty-discover:tasty-discover
